"use client";
import { useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

type Template = { id:string; name:string; category:string; htmlContent:string };
type UploadedFile = { id:string; fileName:string; sizeBytes:number };
export function CampaignBuilder({ defaultSender, templates }: { defaultSender:string; templates:Template[] }) {
  const router=useRouter(); const editor=useRef<HTMLDivElement>(null);
  const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState("");
  const [editorKey,setEditorKey]=useState(0); const [files,setFiles]=useState<UploadedFile[]>([]);
  const [form,setForm]=useState({name:"",subject:"",previewText:"",senderName:"MailFlow user",senderEmail:defaultSender,replyToEmail:"",recipients:"",htmlContent:"<p>Hello {{first_name}},</p><p>Write your message here.</p>"});
  const emails=[...new Set(form.recipients.split(/[\s,;]+/).map(e=>e.trim().toLowerCase()).filter(Boolean))]; const valid=emails.filter(e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e));
  const update=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
  const format=(command:string,value?:string)=>{editor.current?.focus();document.execCommand(command,false,value);};
  const saveEditor=()=>{if(editor.current)update("htmlContent",editor.current.innerHTML);};
  const goNext=()=>{if(step===3)saveEditor();setStep(s=>s+1);};
  const chooseTemplate=(id:string)=>{const selected=templates.find(t=>t.id===id);if(selected){update("htmlContent",selected.htmlContent);setEditorKey(k=>k+1);}};
  async function upload(selected:FileList|null){if(!selected?.length)return;setUploading(true);setError("");for(const file of Array.from(selected)){const body=new FormData();body.append("file",file);const response=await fetch("/api/files",{method:"POST",body});const data=await response.json();if(!response.ok){setError(`${file.name}: ${data.error}`);break;}setFiles(current=>[...current,data.file]);}setUploading(false);}
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,recipients:valid,attachmentIds:files.map(f=>f.id),sendNow:true,permissionConfirmed:true}),signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok){setError(data.error);setBusy(false);return;}router.push(`/dashboard/campaigns/${data.campaign.id}`);router.refresh();}catch{setError("The send request timed out. Check that the website and worker are running, then try again.");setBusy(false);}}
  const steps=["Details","Recipients","Compose","Attachments","Review"];
  return <form onSubmit={submit} className="space-y-6"><div className="flex flex-wrap gap-2" aria-label="Campaign steps">{steps.map((label,i)=><button type="button" key={label} onClick={()=>setStep(i+1)} className={`rounded-full px-4 py-2 text-sm ${step===i+1?"bg-brand-indigo text-white":"bg-white text-slate-600"}`}>{i+1}. {label}</button>)}</div>
    <section className="card p-6">
      {step===1&&<div className="grid gap-4 md:grid-cols-2"><Field label="Campaign name" value={form.name} onChange={v=>update("name",v)}/><Field label="Subject" value={form.subject} onChange={v=>update("subject",v)}/><Field label="Preview text" value={form.previewText} onChange={v=>update("previewText",v)}/><Field label="Sender name" value={form.senderName} onChange={v=>update("senderName",v)}/><Field label="Sender email" type="email" value={form.senderEmail} onChange={v=>update("senderEmail",v)}/><Field label="Reply-to email" type="email" value={form.replyToEmail} onChange={v=>update("replyToEmail",v)}/></div>}
      {step===2&&<div><label className="label" htmlFor="recipients">Recipient emails</label><textarea id="recipients" className="input min-h-48" value={form.recipients} onChange={e=>update("recipients",e.target.value)} placeholder="one@example.com, two@example.com"/><p className="mt-2 text-sm text-slate-500">{valid.length} valid | {emails.length-valid.length} invalid | duplicates removed</p></div>}
      {step===3&&<div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><label className="label min-w-64">Start from a template<select className="input mt-1" defaultValue="" onChange={e=>chooseTemplate(e.target.value)}><option value="">Blank message</option>{templates.map(t=><option value={t.id} key={t.id}>{t.name} - {t.category}</option>)}</select></label><p className="text-xs text-slate-500">Merge fields: {"{{first_name}}, {{last_name}}, {{company}}, {{email}}, {{phone}}"}</p></div><div className="overflow-hidden rounded-xl border border-slate-300 bg-white"><div className="flex flex-wrap gap-1 border-b bg-slate-50 p-2" aria-label="Formatting toolbar"><Tool label="Bold" onClick={()=>format("bold")}/><Tool label="Italic" onClick={()=>format("italic")}/><Tool label="Underline" onClick={()=>format("underline")}/><Tool label="Heading" onClick={()=>format("formatBlock","h2")}/><Tool label="Bullets" onClick={()=>format("insertUnorderedList")}/><Tool label="Numbered" onClick={()=>format("insertOrderedList")}/><Tool label="Link" onClick={()=>{const url=prompt("Link URL");if(url)format("createLink",url)}}/><Tool label="Clear" onClick={()=>format("removeFormat")}/></div><div key={editorKey} ref={editor} contentEditable suppressContentEditableWarning onBlur={saveEditor} className="min-h-72 p-5 text-left text-base leading-7 outline-none" dir="ltr" dangerouslySetInnerHTML={{__html:form.htmlContent}} /></div></div>}
      {step===4&&<div className="space-y-5"><div><h2 className="section-title">File attachments</h2><p className="page-subtitle">PDF, DOCX, XLSX, images, ZIP, and PPTX are supported within your plan limit.</p></div><label className="flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed border-slate-300 p-10 text-center hover:border-brand-indigo"><span className="font-semibold text-slate-800">{uploading?"Uploading...":"Choose files"}</span><span className="mt-1 text-sm text-slate-500">Files are validated and stored privately</span><input type="file" multiple className="sr-only" disabled={uploading} accept=".pdf,.docx,.xlsx,.jpg,.jpeg,.png,.webp,.zip,.pptx" onChange={e=>void upload(e.target.files)}/></label><div className="space-y-2">{files.map(file=><div key={file.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{file.fileName} | {(file.sizeBytes/1024/1024).toFixed(2)} MB</span><button type="button" className="text-red-600" onClick={()=>setFiles(items=>items.filter(i=>i.id!==file.id))}>Remove</button></div>)}</div></div>}
      {step===5&&<div className="space-y-4"><dl className="grid gap-4 md:grid-cols-4"><Summary label="Campaign" value={form.name||"Untitled"}/><Summary label="Subject" value={form.subject||"No subject"}/><Summary label="Recipients" value={String(valid.length)}/><Summary label="Attachments" value={String(files.length)}/></dl><div className="rounded-xl border bg-white p-5" dangerouslySetInnerHTML={{__html:form.htmlContent}}/><label className="flex items-start gap-3 text-sm"><input required type="checkbox" className="mt-1"/>I confirm that I have permission to contact these recipients.</label></div>}
    </section>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-between"><button type="button" disabled={step===1} onClick={()=>setStep(s=>s-1)} className="btn-secondary">Back</button>{step<5?<button type="button" onClick={goNext} className="btn-primary">Continue</button>:<button disabled={busy||!valid.length} className="btn-primary">{busy?"Sending...":"Send campaign"}</button>}</div></form>;
}
function Tool({label,onClick}:{label:string;onClick():void}){return <button type="button" onClick={onClick} className="rounded-md border bg-white px-3 py-1.5 text-xs font-semibold hover:bg-slate-100">{label}</button>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange(v:string):void;type?:string}){const id=label.toLowerCase().replaceAll(" ","-");return <div><label className="label" htmlFor={id}>{label}</label><input required={!label.includes("Reply")&&!label.includes("Preview")} id={id} type={type} className="input" value={value} onChange={e=>onChange(e.target.value)}/></div>}
function Summary({label,value}:{label:string;value:string}){return <div><dt className="text-xs uppercase text-slate-500">{label}</dt><dd className="font-semibold text-slate-900">{value}</dd></div>}



