"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireAdmin, requireUser } from "@/lib/security";
import { hashPassword, isPasswordStrong, verifyPassword } from "@/lib/password";

export async function createTicket(form: FormData) {
  const user = await requireUser(); const subject=String(form.get("subject")??"").trim(); const message=String(form.get("message")??"").trim(); if(subject.length<3||message.length<5) throw new Error("Subject and message are required");
  const ticket=await prisma.supportTicket.create({data:{userId:user.id,subject,category:String(form.get("category")??"General"),priority:String(form.get("priority")??"Normal")}});
  await prisma.ticketReply.create({data:{ticketId:ticket.id,authorId:user.id,message}}); await prisma.notification.create({data:{userId:user.id,type:"SUPPORT",title:"Ticket created",message:`We received: ${subject}`}}); revalidatePath("/dashboard/support");
}
export async function markAllNotificationsRead(){const user=await requireUser();await prisma.notification.updateMany({where:{userId:user.id,readAt:null},data:{readAt:new Date()}});revalidatePath("/dashboard/notifications");}
export async function adminUpdateUser(form:FormData){const admin=await requireAdmin();const userId=String(form.get("userId"));const action=String(form.get("action"));const target=await prisma.user.findUniqueOrThrow({where:{id:userId}});if(target.role==="SUPER_ADMIN"&&(action==="block"||action==="suspend"||action==="delete"))throw new Error("Super administrator accounts are protected");if(userId===admin.id&&action!=="activate")throw new Error("You cannot restrict your own account");if(action==="suspend")await prisma.user.update({where:{id:userId},data:{status:"SUSPENDED"}});if(action==="block")await prisma.user.update({where:{id:userId},data:{status:"BLOCKED"}});if(action==="activate")await prisma.user.update({where:{id:userId},data:{status:"ACTIVE",deletedAt:null}});if(action.startsWith("plan:")){const slug=action.slice(5);const plan=await prisma.plan.findUniqueOrThrow({where:{slug}});await prisma.subscription.upsert({where:{userId},update:{planId:plan.id,status:"ACTIVE",currentPeriodEnd:new Date(Date.now()+365*86400000)},create:{userId,planId:plan.id,status:"ACTIVE",currentPeriodEnd:new Date(Date.now()+365*86400000)}});}if(action==="delete")await prisma.user.delete({where:{id:userId}});await prisma.auditLog.create({data:{actorId:admin.id,action:`USER_${action.toUpperCase()}`,targetType:"User",targetId:userId,metadata:{email:target.email}}});revalidatePath("/admin/users");revalidatePath("/admin");}
export async function updateTicket(form:FormData){const admin=await requireAdmin();const ticketId=String(form.get("ticketId"));const status=String(form.get("status")) as "OPEN"|"IN_PROGRESS"|"WAITING_FOR_USER"|"RESOLVED"|"CLOSED";const message=String(form.get("message")??"").trim();await prisma.supportTicket.update({where:{id:ticketId},data:{status}});if(message)await prisma.ticketReply.create({data:{ticketId,authorId:admin.id,message}});await prisma.auditLog.create({data:{actorId:admin.id,action:"TICKET_UPDATED",targetType:"SupportTicket",targetId:ticketId}});revalidatePath("/admin/support");}

export type AdminCredentialState={error?:string;success?:string};
export async function updateAdminCredentials(_state:AdminCredentialState,form:FormData):Promise<AdminCredentialState>{const admin=await requireAdmin();const currentPassword=String(form.get("currentPassword")??"");const newEmail=String(form.get("newEmail")??"").trim().toLowerCase();const newPassword=String(form.get("newPassword")??"");const confirmPassword=String(form.get("confirmPassword")??"");const record=await prisma.user.findUniqueOrThrow({where:{id:admin.id}});if(!await verifyPassword(currentPassword,record.passwordHash))return{error:"Current password is incorrect."};if(!/^\S+@\S+\.\S+$/.test(newEmail))return{error:"Enter a valid new administrator email."};if(newPassword&&(!isPasswordStrong(newPassword)||newPassword!==confirmPassword))return{error:newPassword!==confirmPassword?"New passwords do not match.":"Use at least 10 characters with uppercase, lowercase, and a number."};const duplicate=await prisma.user.findFirst({where:{email:newEmail,id:{not:admin.id}}});if(duplicate)return{error:"That email address is already in use by another account."};const emailChanged=newEmail!==record.email;await prisma.user.update({where:{id:admin.id},data:{email:newEmail,...(newPassword?{passwordHash:await hashPassword(newPassword)}:{})}});await prisma.auditLog.create({data:{actorId:admin.id,action:"ADMIN_CREDENTIALS_UPDATED",targetType:"User",targetId:admin.id,metadata:{previousEmail:record.email,newEmail,emailChanged,passwordChanged:Boolean(newPassword)}}});revalidatePath("/admin/settings");return{success:`Credentials saved. Administrator email is now ${newEmail}. Log out and sign in with this email.`};}
export async function createAdminTemplate(form:FormData){const admin=await requireAdmin();const name=String(form.get("name")??"").trim();const category=String(form.get("category")??"").trim();const htmlContent=String(form.get("htmlContent")??"").trim();if(name.length<2||category.length<2||htmlContent.length<1)throw new Error("Template name, category, and content are required");const template=await prisma.emailTemplate.create({data:{name,category,htmlContent,isSystem:true}});await prisma.auditLog.create({data:{actorId:admin.id,action:"TEMPLATE_CREATED",targetType:"EmailTemplate",targetId:template.id,metadata:{name}}});revalidatePath("/admin/templates");revalidatePath("/dashboard/templates");}
export async function deleteAdminTemplate(form:FormData){const admin=await requireAdmin();const id=String(form.get("templateId"));const template=await prisma.emailTemplate.findUniqueOrThrow({where:{id}});await prisma.emailTemplate.delete({where:{id}});await prisma.auditLog.create({data:{actorId:admin.id,action:"TEMPLATE_DELETED",targetType:"EmailTemplate",targetId:id,metadata:{name:template.name}}});revalidatePath("/admin/templates");revalidatePath("/dashboard/templates");}
export async function deleteAdminCampaign(form:FormData){const admin=await requireAdmin();const id=String(form.get("campaignId"));const campaign=await prisma.campaign.findUniqueOrThrow({where:{id},include:{user:{select:{email:true}}}});await prisma.$transaction([prisma.queueJob.deleteMany({where:{payload:{path:["campaignId"],equals:id}}}),prisma.campaign.delete({where:{id}})]);await prisma.auditLog.create({data:{actorId:admin.id,action:"CAMPAIGN_RECORD_DELETED",targetType:"Campaign",targetId:id,metadata:{name:campaign.name,owner:campaign.user.email,note:"Database record only; delivered email cannot be recalled"}}});revalidatePath("/admin/campaigns");revalidatePath("/admin");}
export async function updateAdminPlan(form:FormData){const admin=await requireAdmin();const planId=String(form.get("planId"));const integer=(name:string,min=0)=>Math.max(min,Number.parseInt(String(form.get(name)??"0"),10)||0);const name=String(form.get("name")??"").trim();if(name.length<2)throw new Error("Plan name is required");const updated=await prisma.plan.update({where:{id:planId},data:{name,description:String(form.get("description")??"").trim()||null,monthlyPriceCents:integer("monthlyPriceCents"),annualPriceCents:integer("annualPriceCents"),recipientsPerCampaign:integer("recipientsPerCampaign",1),emailsPerDay:integer("emailsPerDay",1),emailsPerMonth:integer("emailsPerMonth",1),contactLimit:integer("contactLimit",1),storageLimitMb:integer("storageLimitMb",1),attachmentLimitMb:integer("attachmentLimitMb",1),templateLimit:integer("templateLimit",1),teamMemberLimit:integer("teamMemberLimit",1),apiAccess:form.get("apiAccess")==="on",analyticsAccess:form.get("analyticsAccess")==="on",brandingRemoval:form.get("brandingRemoval")==="on",customDomainAccess:form.get("customDomainAccess")==="on",isActive:form.get("isActive")==="on",isFeatured:form.get("isFeatured")==="on"}});await prisma.auditLog.create({data:{actorId:admin.id,action:"PLAN_UPDATED",targetType:"Plan",targetId:planId,metadata:{name:updated.name}}});revalidatePath("/admin/plans");revalidatePath("/pricing");revalidatePath("/dashboard/subscription");redirect(`/admin/plans?saved=${planId}`);}
export async function updateUserProfile(form:FormData){const user=await requireUser();const fullName=String(form.get("fullName")??"").trim();if(fullName.length<2)throw new Error("Full name is required");const requestedTimeZone=String(form.get("timeZone")??"UTC");const supportedTimeZones=new Set(Intl.supportedValuesOf("timeZone"));const timeZone=requestedTimeZone==="UTC"||supportedTimeZones.has(requestedTimeZone)?requestedTimeZone:"UTC";await prisma.user.update({where:{id:user.id},data:{fullName,companyName:String(form.get("companyName")??"").trim()||null,country:String(form.get("country")??"").trim()||null,timeZone}});const senderEmail=String(form.get("senderEmail")??"").trim().toLowerCase();const senderName=String(form.get("senderName")??"").trim();if(senderEmail&&/^\S+@\S+\.\S+$/.test(senderEmail)&&senderName){const existing=await prisma.senderIdentity.findFirst({where:{userId:user.id,fromEmail:senderEmail}});if(existing)await prisma.senderIdentity.update({where:{id:existing.id},data:{fromName:senderName}});else await prisma.senderIdentity.create({data:{userId:user.id,fromName:senderName,fromEmail:senderEmail,isVerified:senderEmail===user.email}});}await prisma.auditLog.create({data:{actorId:user.id,action:"PROFILE_UPDATED",targetType:"User",targetId:user.id,metadata:{timeZone}}});revalidatePath("/dashboard/settings");}
export type UserPasswordState={error?:string;success?:string};
export async function updateUserPassword(_state:UserPasswordState,form:FormData):Promise<UserPasswordState>{const user=await requireUser();const current=String(form.get("currentPassword")??"");const password=String(form.get("newPassword")??"");const confirm=String(form.get("confirmPassword")??"");const record=await prisma.user.findUniqueOrThrow({where:{id:user.id}});if(!await verifyPassword(current,record.passwordHash))return{error:"Current password is incorrect."};if(!isPasswordStrong(password))return{error:"Use at least 10 characters with uppercase, lowercase, and a number."};if(password!==confirm)return{error:"New passwords do not match."};if(await verifyPassword(password,record.passwordHash))return{error:"Choose a password different from your current password."};await prisma.user.update({where:{id:user.id},data:{passwordHash:await hashPassword(password),failedLoginCount:0,lockedUntil:null}});await prisma.auditLog.create({data:{actorId:user.id,action:"PASSWORD_CHANGED",targetType:"User",targetId:user.id}});return{success:"Password updated. Signing you out now..."};}

